package com.trendsole.model;

// JPA annotations
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;

// Lombok annotations
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * CartItem Entity Class
 *
 * What it does:
 * - Represents the "cart" table in the database.
 * - Each CartItem = one product added to the shopping cart.
 * - It has a relationship with the Product entity (Many cart items can have the same product).
 *
 * Annotations:
 * - @Entity     → This class maps to a database table.
 * - @Table      → The table name in MySQL is "cart".
 * - @ManyToOne  → Many cart items can point to ONE product.
 * - @JoinColumn → Specifies the foreign key column in the cart table.
 */
@Entity
@Table(name = "cart")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CartItem {

    /**
     * Primary key - auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * @ManyToOne → Many cart items can refer to the SAME product.
     * Example: 3 users can add "Nike Air Max" to their cart.
     *
     * @JoinColumn(name = "product_id") → Creates a foreign key column "product_id"
     * in the cart table that links to the products table.
     */
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /**
     * How many of this product the user wants to buy.
     * Default is 1 (set in schema.sql).
     */
    @Column(nullable = false)
    private Integer quantity;
}
