package com.trendsole.model;

// JPA annotations
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Column;

// Lombok annotations
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

// For date handling
import java.time.LocalDateTime;

/**
 * Order Entity Class
 *
 * What it does:
 * - Represents the "orders" table in the database.
 * - Each Order = one completed purchase by a customer.
 * - Stores customer details and the total amount paid.
 *
 * Annotations:
 * - @Entity → This class maps to a database table.
 * - @Table(name = "orders") → Maps to the "orders" table.
 *   Note: We use "orders" (not "order") because "order" is a reserved keyword in SQL.
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    /**
     * Primary key - auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the customer who placed the order.
     */
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    /**
     * Customer's email address for order confirmation.
     */
    @Column(nullable = false)
    private String email;

    /**
     * Delivery address where the order will be shipped.
     * @Column(columnDefinition = "TEXT") → Allows long address text.
     */
    @Column(columnDefinition = "TEXT", nullable = false)
    private String address;

    /**
     * Total amount of the order in rupees (e.g., 25998.00).
     */
    @Column(name = "total_amount", nullable = false)
    private Double totalAmount;

    /**
     * Date and time when the order was placed.
     * LocalDateTime stores both date and time (e.g., 2026-07-08T20:10:00).
     */
    @Column(name = "order_date")
    private LocalDateTime orderDate;
}
